name: Deploy API

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: primerbrand.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t primerbrand.azurecr.io/socialassetapi:${{ github.sha }}
          docker push primerbrand.azurecr.io/socialassetapi:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "socialassetapi"
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          images: "primerbrand.azurecr.io/socialassetapi:${{ github.sha }}"
