name: Deploy API

on:
  push:
    branches: ["main"]
    paths:
      - api/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: primerbrand.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image to registry
        env:
          OAUTH_CLIENT_ID: "${{ secrets.OAUTH_CLIENT_ID }}"
          OAUTH_CLIENT_SECRET: "${{ secrets.OAUTH_CLIENT_SECRET }}"
          OAUTH_REDIRECT_URI: "${{ secrets.OAUTH_REDIRECT_URI }}"
          WEB_APP_URL: "${{ secrets.WEB_APP_URL }}"
        run: |
          docker build ./api -t primerbrand.azurecr.io/socialassetapi:${{ github.sha }} --build-arg OAUTH_CLIENT_ID_ARG=${{ secrets.OAUTH_CLIENT_ID }} OAUTH_CLIENT_SECRET_ARG=${{ secrets.OAUTH_CLIENT_SECRET }}
          docker push primerbrand.azurecr.io/socialassetapi:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "assetgenerator"
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          images: "primerbrand.azurecr.io/socialassetapi:${{ github.sha }}"
